module.exports = {
    "get-started": "Getting started",
    "inline-data": "Inline data extension",
    "images": "Images extension",
    "scripts": "Scripts extension",
    "child-templates": "Child templates extension",
    "api": "API",
    "reports": "Reports extension",
    "net-client": ".NET client",
    "import-export": "Import Export extension",
    "net-embedded": ".NET embedded",
    "visual-studio-extension": "Visual Studio Extension",
    "phantom-pdf": "Phantom pdf recipe",
    "fop-pdf": "Fop pdf recipe",
    "html": "Html recipe",
    "engines": "Engines",
    "jsrender": "jsrender templating engine",
    "handlebars": "handlebars templating engine",
    "adapting-jsreport": "Adapting jsreport",
    "nodejs-client": "node.js client",
    "pdf-reports-in-nodejs": "Pdf reports in node.js",
    "authentication": "Authentication",
    "authorization": "Authorization",
    "client-html": "Client html recipe",
    "embedding": "Embedding",
    "xlsx": "Xlsx recipe",
    "html-to-xlsx": "Converting html to xlsx",
    "text": "Text recipe",
    "reports-in-sharepoint": "Reports in SharePoint",
    "scheduling": "Scheduling",
    "asp-net-mvc": "ASP.NET MVC",
    "wrapped-html": "Wrapped html recipe",
    "public-templates": "Public templates",
    "live-reports": "Live reports",
    "periodical-report-sending-through-email": "Periodical report sending through email",
    "customizable-dashboards-integration": "Customizable dashboards integration",
    "resources": "Resources",
    "faq": "FAQ",
    "configuration": "Configuration",
    "custom-extension": "Custom Extension",
    "client-app": "Client Application",
    "wkhtmltopdf": "wkhtmltopdf recipe",
    "ejs": "EJS",
    "custom-engine": "Custom Engine",
    "custom-recipe": "Custom Recipe",
    "html-to-text": "Html to Text recipe",
    "windows-single-executable": "Windows single executable",
    "studio-api-reference": "Studio API reference",
    "extending-studio": "Extending studio",
    "upgrading-to-10": "Upgrading to 1.0",
    "html-with-browser-client": "Html with browser client",
    "browser-client": "Browser client",
    "dynamic-excel-pivot-table": "Dynamic excel pivot table",
    "assets": "Assets",
    "import-export": "Import - Export",
    "tags": "Tags",
    "online-limits": "Online limits",
    "cli": "Command-line interface",
    "single-file-executable": "Single file executale",
    "online-faq": "Online FAQ",
    "dotnet-client": ".Net Client v2 preview",
    "dotnet-aspnetcore": "asp.net core middleware and filter",
    "dotnet-local": ".Net local reporting",
    "dotnet-v2": ".NET sdk for jsreport"
};