module.exports = {
    "get-started": "Getting started",
    "inline-data": "Inline data extension",
    "images": "Images extension",
    "scripts": "Scripts extension",
    "phantom-recipe": "Phantom resipe",
    "child-templates": "Child templates extension",
    "api": "API",
    "reports": "Reports extension",
    "net-client": ".NET client",
    "import-export": "Import Export extension",
    "net-embedded": ".NET embedded",
    "visual-studio-extension": "Visual Studio Extension",
    "phantom-pdf": "Phantom pdf recipe",
    "fop-pdf": "Fop pdf recipe",
    "html": "Html recipe",
    "engines": "Engines",
    "jsrender": "jsrender templating engine",
    "handlebars": "handlebars templating engine",
    "adapting-jsreport": "Adapting jsreport",
    "nodejs-client": "node.js client",
    "pdf-reports-in-nodejs": "Pdf reports in node.js",
    "authentication": "Authentication",
    "authorization": "Authorization",
    "client-html": "Client html recipe",
    "embedding": "Embedding",
    "xlsx": "Xlsx recipe",
    "html-to-xlsx": "Converting html to xlsx",
    "text": "Text recipe",
    "reports-in-sharepoint": "Reports in SharePoint",
    "scheduling": "Scheduling",
    "asp-net-mvc": "ASP.NET MVC"

};