name: main 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.5.0
        with:
          mongodb-version: '4.2'

      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: ./deploy.sh